apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backsite-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backsite
        version: v1
    spec:
      containers:
      - name: flask
        image: riskiwah/canary:v1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backsite-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backsite
        version: v2
    spec:
      containers:
      - name: flask
        image: riskiwah/canary:v2